### ISSUE TITLE
bootstrap scss issue

### ISSUE THREAD

**Issue by Shwshank** [Shwshank/QCI-Collect-frontend#1]
![bootstrap_issue](https://user-images.githubusercontent.com/7690226/34474885-87c6b43c-efab-11e7-9e57-b6f413a10b3d.png)
Please resolve ASAP!

**Comment by Shwshank** [comment]
1. @deepak-ranolia at the EOD plz check if there is any bug in the code or not by running the project in a different directory. 
2. @deepak-ranolia  plz mention the detailed description of  updated code in the commit message. 
3. @deepak-ranolia comments are missing as discussed. Plz mention comments about the variables and div through out the project.

**Comment by deepak-ranolia** [comment]
**@Shwshank  checked in a different directory, but got another error as**

ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./node_modules/bootstrap/scss/bootstrap.scss
Module build failed: BrowserslistError: Unknown browser major
    at error (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/browserslist/index.js:37:11)
    at Function.browserslist.checkName (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/browserslist/index.js:320:18)
    at Function.select (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/browserslist/index.js:438:37)
    at /usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/browserslist/index.js:207:41
    at Array.forEach (<anonymous>)
    at browserslist (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/browserslist/index.js:196:13)
    at Browsers.parse (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/autoprefixer/lib/browsers.js:44:14)
    at new Browsers (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/autoprefixer/lib/browsers.js:39:28)
    at loadPrefixes (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/autoprefixer/lib/autoprefixer.js:56:18)
    at plugin (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/autoprefixer/lib/autoprefixer.js:62:18)
    at LazyResult.run (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/postcss/lib/lazy-result.js:201:22)
    at processing.Promise.then._this2.processed (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/postcss/lib/lazy-result.js:228:20)
    at new Promise (<anonymous>)
    at LazyResult.async (/usr/local/lib/node_modules/collect/QCI-Collect-frontend/node_modules/postcss/lib/lazy-result.js:225:27)
 @ ./node_modules/bootstrap/scss/bootstrap.scss 4:14-160
 @ multi ./node_modules/ng2-toastr/bundles/ng2-toastr.min.css ./node_modules/bootstrap/scss/bootstrap.scss ./src/styles.scss


** and in order to resolve this issue:
1. npm uninstall bootstrap --save
2. npm install bootstrap@4.0.0-beta.2 --save

But still figuring out why you are getting this error ! **

**Comment by offline-pixel** [comment]
@Shwshank 
ADD
_**@import "~bootstrap/scss/_functions.scss";**_ in styles.scss file
than in terminal
1. **npm uninstall bootstrap --save**
2. **npm install bootstrap@4.0.0-beta.2 --save**
